version: "3"
services:
        zookeeper:
                image: confluentinc/cp-zookeeper:6.1.1
                hostname: zookeeper
                ports:
                        - "2181:2181"
                environment:
                        ZOOKEEPER_CLIENT_PORT: 2181
                        ZOOKEEPER_TICK_TIME: 2000
        kafka:
                image: confluentinc/cp-kafka:6.1.1
                hostname: kafka
                depends_on:
                        - zookeeper
                ports:
                        - "9092:9092"
                        - "9101:9101"
                environment:
                        KAFKA_BROKER_ID: 1
                        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
                        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
                        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
                        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        producer:
                container_name: Producer
                image: tomcat:10
                volumes:
                        - ./target/JavaTest-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
                ports:
                        - "8080:8080"
        consumer:
                container_name: Consumer
                image: tomcat:10
                depends_on:
                        - producer
                volumes:
                        - ./target/JavaTest-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
                ports:
                        - "8081:8080"